import { useEffect, useRef, useState, type CSSProperties, type FormEvent } from 'react';
import {
  ArrowDown, ArrowRight, ArrowUp, BriefcaseBusiness, Github, GraduationCap,
  Linkedin, Mail, Menu, Send, Sparkles, X,
} from 'lucide-react';
import { CheckCircle2 } from 'lucide-react';

const projects = [
  { title:'Hostel Management System', tag:'Java · OOP', description:'A console-based system for managing student records, room allocation, fee management, and complaint handling using Java and object-oriented programming principles.', image:'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1000&q=82' },
  { title:'Typing Speed Test', tag:'C++ · Standard Library', description:'A typing test application that measures typing speed and accuracy in real time and calculates WPM and accuracy percentage.', image:'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1000&q=82' },
  { title:'Traffic Light Control System', tag:'C++ · OOP', description:'A traffic-light simulation designed with object-oriented programming to control intersection flow through timing and state transitions.', image:'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=1000&q=82' },
  { title:'Vending Machine using FSM', tag:'Digital Logic Design · FSM', description:'A vending machine system implemented with a finite state machine to manage idle, coin inserted, item selected, and dispensing states.', image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1000&q=82' },
  { title:'Medical Image Processing & TBI Dataset Curation', tag:'Internship · Python', description:'Worked with a CoSOD head CT dataset for Traumatic Brain Injury, including clinical parameter evaluation, region separation, DICOM metadata sorting, pydicom, OpenCV, pandas, and matplotlib.', image:'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1000&q=82' },
];
const skillGroups = [
  { title:'PROGRAMMING', items:[
    {name:'C',mark:'C',tone:'blue',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/c/c-original.svg'},
    {name:'C++',mark:'C++',tone:'violet',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cplusplus/cplusplus-original.svg'},
    {name:'Java',mark:'☕',tone:'orange',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original.svg'},
    {name:'Python',mark:'Py',tone:'yellow',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg'}]},
  { title:'DATABASE', items:[{name:'MySQL',mark:'SQL',tone:'cyan',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg'}]},
  { title:'AI / ML', items:[
    {name:'Artificial Intelligence',mark:'AI',tone:'green',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pytorch/pytorch-original.svg'},
    {name:'Machine Learning',mark:'ML',tone:'purple',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/scikitlearn/scikitlearn-original.svg'},
    {name:'Computer Vision',mark:'CV',tone:'red',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/opencv/opencv-original.svg'},
    {name:'OpenCV',mark:'CV',tone:'rose',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/opencv/opencv-original.svg'}]},
  { title:'SOFTWARE ENGINEERING', items:[
    {name:'SRS',mark:'SRS',tone:'steel'},{name:'HCI',mark:'HCI',tone:'pink'},
    {name:'UI/UX Design',mark:'UX',tone:'indigo',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg'},
    {name:'Software Requirements Engineering',mark:'REQ',tone:'teal'}]},
  { title:'DEVELOPMENT', items:[
    {name:'App Development',mark:'APP',tone:'lime'},
    {name:'Web Development',mark:'</>',tone:'sky',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg'},
    {name:'pandas',mark:'pd',tone:'blue',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pandas/pandas-original.svg'},
    {name:'pydicom',mark:'D',tone:'gold'},
    {name:'matplotlib',mark:'M',tone:'orange',icon:'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/matplotlib/matplotlib-original.svg'}]},
];
const coursework=['Object-Oriented Programming (OOP)','Data Structures & Algorithms (DSA)','Software Requirements Engineering & SRS','Mobile Development','Software Construction and Development','Software Quality Engineering','Operating Systems','Design and Analysis of Algorithms'];
const approaches=[['01','Learn & Understand','I start by understanding the problem, users, requirements, and constraints before choosing the right technical direction.'],['02','Build & Iterate','I turn ideas into working software, test continuously, and refine the experience through practical iteration and feedback.'],['03','Improve & Deliver','I focus on clean implementation, usability, reliability, and delivering a solution that is easy to understand and maintain.']];
type ContactStatus='idle'|'sending'|'sent'|'error';

function App(){
  const [showAll,setShowAll]=useState(false),[menuOpen,setMenuOpen]=useState(false),[navVisible,setNavVisible]=useState(true),[contactOpen,setContactOpen]=useState(false),[contactStatus,setContactStatus]=useState<ContactStatus>('idle'),[contactError,setContactError]=useState('');
  const lastScrollY=useRef(0),cursorTrail=useRef<HTMLDivElement>(null),lastTrailPoint=useRef<{x:number;y:number}|null>(null),lastTrailTime=useRef(0),menuRef=useRef<HTMLElement>(null),menuButtonRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>{const onScroll=()=>{const current=window.scrollY;if(current<90)setNavVisible(true);else if(current>lastScrollY.current+4)setNavVisible(false);else if(current<lastScrollY.current-4)setNavVisible(true);lastScrollY.current=current;};const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('is-visible');}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>revealObserver.observe(e));window.addEventListener('scroll',onScroll,{passive:true});return()=>{window.removeEventListener('scroll',onScroll);revealObserver.disconnect();};},[]);
  useEffect(()=>{const onPointerMove=(event:PointerEvent)=>{const{clientX,clientY}=event;const now=performance.now(),previous=lastTrailPoint.current;if(cursorTrail.current&&previous&&now-lastTrailTime.current>70){const dx=clientX-previous.x,dy=clientY-previous.y,distance=Math.hypot(dx,dy);if(distance>12){const line=document.createElement('span');line.className='cursor-trail-line';line.style.left=previous.x+'px';line.style.top=previous.y+'px';line.style.width=Math.min(distance,65)+'px';line.style.transform='rotate('+(Math.atan2(dy,dx)*180/Math.PI)+'deg)';cursorTrail.current.appendChild(line);window.setTimeout(()=>line.remove(),1100);lastTrailTime.current=now;}}lastTrailPoint.current={x:clientX,y:clientY};};window.addEventListener('pointermove',onPointerMove,{passive:true});return()=>{window.removeEventListener('pointermove',onPointerMove);};},[]);
  useEffect(()=>{if(!menuOpen)return;const onPointerDown=(event:PointerEvent)=>{const target=event.target;if(target instanceof Node&&!menuRef.current?.contains(target)&&!menuButtonRef.current?.contains(target))setMenuOpen(false);};const onKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape')setMenuOpen(false);};const onResize=()=>{if(window.matchMedia('(min-width: 768px)').matches)setMenuOpen(false);};document.addEventListener('pointerdown',onPointerDown);document.addEventListener('keydown',onKeyDown);window.addEventListener('resize',onResize);return()=>{document.removeEventListener('pointerdown',onPointerDown);document.removeEventListener('keydown',onKeyDown);window.removeEventListener('resize',onResize);};},[menuOpen]);
  useEffect(()=>{if(!contactOpen)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setContactOpen(false)};document.addEventListener('keydown',onKey);document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',onKey);document.body.style.overflow='';};},[contactOpen]);
  const go=(id:string)=>{setMenuOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});};
  const openContact=()=>{setContactStatus('idle');setContactError('');setContactOpen(true);};
  const visibleProjects=showAll?projects:projects.slice(0,3);
  const handleContactSubmit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setContactStatus('sending');setContactError('');const form=event.currentTarget,formData=new FormData(form);const payload={name:String(formData.get('name')||''),email:String(formData.get('email')||''),subject:String(formData.get('subject')||''),message:String(formData.get('message')||'')};try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const responseText=await response.text();let data:{error?:string;message?:string}={};try{data=JSON.parse(responseText)}catch{}if(!response.ok)throw new Error(data.error||data.message||responseText||`Request failed with status ${response.status}.`);setContactStatus('sent');form.reset();}catch(err){setContactError(err instanceof Error?err.message:'Something went wrong while sending. Please try again.');setContactStatus('error');}};
  return <div className="site">
    <div ref={cursorTrail} className="cursor-trail" aria-hidden="true"/><div className="ambient ambient-one" aria-hidden="true"/><div className="ambient ambient-two" aria-hidden="true"/>
    <header className={'floating-nav '+(navVisible?'nav-visible':'nav-hidden')}><nav ref={menuRef} id="primary-navigation" className={menuOpen?'nav-menu open':'nav-menu'} aria-label="Primary navigation"><a href="#projects" onClick={()=>go('projects')}>Projects</a><a href="#skills" onClick={()=>go('skills')}>Skills</a><a href="#experience" onClick={()=>go('experience')}>Experience</a><a href="#contact" onClick={()=>go('contact')}>Contact</a></nav><button ref={menuButtonRef} className="mobile-menu" type="button" onClick={()=>setMenuOpen(v=>!v)} aria-label={menuOpen?'Close menu':'Open menu'} aria-expanded={menuOpen} aria-controls="primary-navigation">{menuOpen?<X size={20}/>:<Menu size={20}/>}</button></header>
    <main>
      <section id="home" className="hero"><div className="hero-copy reveal is-visible"><span className="hero-kicker">SOFTWARE ENGINEERING STUDENT</span><h1>Muhammad Shariq<br/>Shakeel</h1><p>I’m a motivated Software Engineering student at Air University, Aerospace and Aviation Campus, Kamra. I’m eager to apply my programming skills, gain hands-on industry experience, and contribute to real software development projects.<span className="mobile-intro-extra"> I’m particularly interested in AI and computer vision, and enjoy turning technical ideas into useful software.</span><span className="mobile-intro-followup"> I’m eager to keep learning, collaborate, and contribute to thoughtful projects with real-world impact.</span><span className="mobile-intro-extra-small"> I’m especially interested in AI and computer vision.</span></p><div className="social-follow"><span>Follow me</span><i/><a href="https://github.com/MuhammadShariqShakeel" target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={19}/></a><a href="https://www.linkedin.com/in/muhammadshariqshakeel" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={19}/></a></div></div>
        <div className="hero-portrait reveal is-visible"><div className="portrait-glow"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="outer-pulse pulse-one"/><span className="outer-pulse pulse-two"/><span className="profile-marker marker-two" aria-hidden="true"/><span className="profile-marker marker-three" aria-hidden="true"/><div className="portrait-ring"><img src="/resources/profile-photo.jpg" alt="Muhammad Shariq Shakeel" className="portrait-image"/></div><div className="work-badge"><b>Open to Work</b></div></div><button className="scroll-cue" type="button" aria-label="Scroll to projects" onClick={()=>go('projects')}><span>SCROLL</span><ArrowDown size={22}/></button>
      </section>
      <section id="projects" className="section projects"><SectionTitle kicker="SELECTED WORK" title="PROJECTS"/><div className="project-grid">{visibleProjects.map((project,index)=><article className={'project-card reveal '+(showAll?'is-visible':'')} style={{'--delay':index*80+'ms'} as CSSProperties} key={project.title}><div className="project-image"><img src={project.image} alt="" loading="lazy"/><div className="image-fade"/><span className="project-number">0{index+1}</span><span className="project-corner"/></div><div className="project-content"><span className="project-tag">{project.tag}</span><h3>{project.title}</h3><p>{project.description}</p><button className="live-btn" type="button" onClick={openContact}>Discuss Project <ArrowRight size={15}/></button></div></article>)}</div><button className="outline-pill" type="button" onClick={()=>setShowAll(v=>!v)} aria-expanded={showAll}>{showAll?'Show Less':'Show More Projects'} <ArrowRight size={15}/></button></section>
      <section id="skills" className="section skills"><SectionTitle kicker="TECHNICAL TOOLKIT" title="SKILLS"/><div className="skills-groups">{skillGroups.map(group=><div className="skill-group reveal" key={group.title}><h3>{group.title}</h3><div className="skill-chips">{group.items.map(item=><span className="skill-chip" key={item.name}><span className={'skill-logo '+item.tone}>{item.icon?<img src={item.icon} alt="" loading="lazy"/>:<span>{item.mark}</span>}<i/></span>{item.name}</span>)}</div></div>)}</div><div className="coursework reveal"><div className="coursework-heading"><GraduationCap size={19}/><span>RELEVANT COURSEWORK</span><small>CORE STUDIES</small></div><div className="coursework-list">{coursework.map((item,index)=><span key={item}><b>{String(index+1).padStart(2,'0')}</b><i/><strong>{item}</strong></span>)}</div></div><div className="count-pill"><strong>21</strong> SKILLS &amp; TOPICS</div></section>
      <section id="experience" className="section experience"><SectionTitle kicker="EDUCATION & EXPERIENCE" title="EXPERIENCE"/><div className="experience-layout"><article className="experience-card reveal"><div className="experience-icon"><BriefcaseBusiness size={21}/></div><div className="experience-meta"><span>INTERNSHIP</span><h3>Medical Image Processing &amp; TBI Dataset Curation</h3><small>Python · Medical Imaging</small><p>Worked with the CoSOD head CT dataset for Traumatic Brain Injury, focusing on clinical parameter evaluation, image/data preprocessing, DICOM metadata sorting, pydicom, pandas, matplotlib, and OpenCV/computer vision.</p></div></article><article className="education-card reveal"><div className="experience-icon"><GraduationCap size={21}/></div><div className="experience-meta"><span>2024 — 2028</span><h3>Bachelor of Science in Software Engineering</h3><small>Air University · Aerospace and Aviation Campus, Kamra</small><p>CGPA: 3.30 / 4.00</p></div></article></div><div className="strengths reveal"><span>QUICK LEARNER</span><span>TIME MANAGEMENT</span><span>PROBLEM SOLVER</span><span>TEAM PLAYER</span><span>STRONG WORK ETHIC</span></div></section>
      <section id="approach" className="section approach"><SectionTitle kicker="HOW I WORK" title="APPROACH"/><div className="approach-grid">{approaches.map(([number,title,text],index)=><article className={'approach-card reveal '+(index===1?'active':'')} key={number}><strong>{number}</strong><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section id="contact" className="contact"><span className="contact-kicker"><Sparkles size={13}/> LET’S BUILD SOMETHING</span><h2>Ready to turn your<br/><em>idea into software?</em></h2><p>I’m excited to explore opportunities where I can learn, contribute, and grow through meaningful software development work.</p><div className="contact-buttons"><button className="contact-btn primary" type="button" onClick={openContact}><Mail size={16}/> Get in Touch <ArrowRight size={15}/></button></div><a className="contact-back-top" href="#home">Back to top <ArrowUp size={19}/></a></section>
    </main>
    <footer className="footer"><div className="footer-socials"><a href="https://github.com/MuhammadShariqShakeel" target="_blank" rel="noreferrer" aria-label="GitHub"><Github size={21}/></a><a href="https://www.linkedin.com/in/muhammadshariqshakeel" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin size={21}/></a></div><span className="footer-note">Muhammad Shariq Shakeel · Software Engineering Student</span></footer>
    {contactOpen&&<div className="contact-modal-backdrop" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)setContactOpen(false)}}><div className="contact-modal" role="dialog" aria-modal="true" aria-labelledby="contact-title"><button className="modal-close" type="button" onClick={()=>setContactOpen(false)} aria-label="Close contact form"><X size={20}/></button><div className="modal-kicker"><Send size={14}/> SEND A MESSAGE</div><h2 id="contact-title">Let’s talk.</h2><p>Your message will be sent to <strong>shariqofficial6@gmail.com</strong>.</p>{contactStatus==='sent'?<div className="form-success"><CheckCircle2 size={42}/><h3>Message sent</h3><p>Thanks for reaching out. Your message has been submitted successfully.</p><button className="contact-btn primary" type="button" onClick={()=>setContactOpen(false)}>Close</button></div>:<form onSubmit={handleContactSubmit}><div className="form-grid"><label>Your name<input name="name" type="text" placeholder="Muhammad Ali" required/></label><label>Your email<input name="email" type="email" placeholder="you@example.com" required/></label></div><label>Subject<input name="subject" type="text" placeholder="Project opportunity" required/></label><label>Message<textarea name="message" rows={5} placeholder="Tell me a little about your idea..." required/></label>{contactStatus==='error'&&<div className="form-error">{contactError}</div>}<button className="send-message" type="submit" disabled={contactStatus==='sending'}>{contactStatus==='sending'?'Sending…':'Send Message'} <Send size={16}/></button><small className="form-note">Securely sent through Resend. You stay on this page.</small></form>}</div></div>}
  </div>;
}
function SectionTitle({kicker,title}:{kicker?:string;title:string}){return <div className="section-title reveal">{kicker&&<span>{kicker}</span>}<h2>{title}</h2><i/></div>}
export default App;
